import Image from 'next/image';

const MARKET_FEEDS_SRC = '/brand/marketfeeds.webp' as const;

const MECHANISM_CARDS = [
  {
    label: 'AI SCANS',
    copy: 'New launches are continuously analysed for narrative strength and lore.',
  },
  {
    label: 'MARKETS RANK',
    copy: 'The strongest launches rise based on quality and live market signals.',
  },
  {
    label: 'SCOOP DEPLOYS',
    copy: 'Creator rewards earned by SCOOP are used for selective onchain buys.',
  },
  {
    label: 'VALUE RECYCLES',
    copy: 'Revenue generated by the ecosystem is put back into emerging markets.',
  },
] as const;

/**
 * Homepage economics module — creator-reward recycling loop + marketfeeds artwork.
 */
export function ProtocolSection() {
  return (
    <section
      aria-labelledby="protocol-heading"
      className="bg-[var(--scoop-green)] text-[var(--scoop-green-contrast)]"
      data-testid="protocol-economics"
    >
      <div className="mx-auto max-w-[1400px] px-4 py-14 md:px-8 md:py-20 lg:px-10 lg:py-24">
        <div className="grid items-center gap-10 md:grid-cols-12 md:gap-12 lg:gap-16">
          <div className="md:col-span-5 lg:col-span-5">
            <p className="font-mono text-[12px] uppercase tracking-[0.2em]">
              SCOOP ECONOMICS
            </p>
            <h2
              id="protocol-heading"
              className="mt-5 max-w-xl font-serif text-4xl leading-[1.05] tracking-tight md:mt-6 md:text-5xl lg:text-6xl xl:text-7xl"
            >
              The market feeds the market.
            </h2>
            <div className="mt-6 max-w-md space-y-4 text-base leading-snug md:mt-8 md:text-lg md:leading-snug">
              <p>
                SCOOP earns creator rewards from its own native token. Instead of treating those
                rewards as passive revenue, we put them back into the network.
              </p>
              <p>
                Our AI scans new launches for strong lore, compelling narratives and early market
                signals. The launches that stand out can receive strategic onchain buys funded by
                SCOOP&apos;s creator rewards.
              </p>
              <p>Better lore. Better launches. More attention.</p>
              <p>The stronger the market, the more value flows back into the ecosystem.</p>
            </div>

            <dl className="mt-10 grid max-w-md grid-cols-1 gap-5 sm:grid-cols-2 md:mt-12">
              {MECHANISM_CARDS.map((card) => (
                <div key={card.label} data-testid="protocol-mechanism-card">
                  <dt className="font-mono text-[11px] uppercase tracking-[0.14em]">
                    {card.label}
                  </dt>
                  <dd className="mt-1.5 text-sm leading-snug text-[var(--scoop-green-contrast)]/85 md:text-[15px]">
                    {card.copy}
                  </dd>
                </div>
              ))}
            </dl>
          </div>

          <div className="md:col-span-7 lg:col-span-7">
            <div className="relative mx-auto aspect-square w-full max-w-[36rem] md:ml-auto md:max-w-none">
              <Image
                src={MARKET_FEEDS_SRC}
                alt="Artwork showing market activity feeding back into the protocol"
                width={1000}
                height={1000}
                sizes="(max-width: 768px) 92vw, (max-width: 1400px) 52vw, 720px"
                className="h-auto w-full object-contain"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
